" Example Vim configuration.
" Copy or symlink to ~/.vimrc or ~/_vimrc.
" to get pink.vim to work
set t_Co=256

" I'd like to use tab to autocomplete instead of Ctrl-p

map <Tab> <C-p>

set nocompatible                  " Must come first because it changes other options.

silent! call pathogen#runtime_append_all_bundles()

syntax enable                     " Turn on syntax highlighting.
filetype plugin indent on         " Turn on file type detection.

filetype plugin on                 " for the R vim add on 

runtime macros/matchit.vim        " Load the matchit plugin.

set showcmd                       " Display incomplete commands.
set showmode                      " Display the mode you're in.

set backspace=indent,eol,start    " Intuitive backspacing.

set hidden                        " Handle multiple buffers better.

set wildmenu                      " Enhanced command line completion.
set wildmode=list:longest         " Complete files like a shell.

set ignorecase                    " Case-insensitive searching.
set smartcase                     " But case-sensitive if expression contains a capital letter.

set number                        " Show line numbers.
set ruler                         " Show cursor position.

set incsearch                     " Highlight matches as you type.
set hlsearch                      " Highlight matches.
:nnoremap <silent> <C-l> :noh<CR><C-l>

set wrap                          " Turn on line wrapping.
set scrolloff=3                   " Show 3 lines of context around the cursor.

set title                         " Set the terminal's title

set visualbell                    " No beeping.

set nobackup                      " Don't make a backup before overwriting a file.
set nowritebackup                 " And again.
set directory=$HOME/.vim/tmp//,.  " Keep swap files in one location

" UNCOMMENT TO USE
set tabstop=2                    " Global tab width.
set shiftwidth=2                 " And again, related.
set expandtab                    " Use spaces instead of tabs

set laststatus=2                  " Show the status line all the time
" Useful status information at bottom of screen
set statusline=[%n]\ %<%.99f\ %h%w%m%r%y\ %{fugitive#statusline()}%{exists('*CapsLockStatusline')?CapsLockStatusline():''}%=%-16(\ %l,%c-%v\ %)%P

colorscheme vividchalk
" colorscheme topfunky-light
"colorscheme railscasts	

let mapleader = ","

" Tab mappings.
" map <leader>tt :tabnew<cr>
" map <leader>te :tabedit
" map <leader>tc :tabclose<cr>
" map <leader>to :tabonly<cr>
" map <leader>tn :tabnext<cr>
" map <leader>tp :tabprevious<cr>
" map <leader>tf :tabfirst<cr>
" map <leader>tl :tablast<cr>
" map <leader>tm :tabmove
" map <leader>test  :!bash script/test
map <leader>xl <c-x>  <c-l> 

" map make stuff

map <leader>m :!make <cr>
map <leader>y :!python % <cr>
map <leader>r :!ruby % <cr>
map <leader>c :!g++ % <cr>
map <leader>a :!./a.out <cr>

" map screen jumping

map <leader>h <c-w>h
map <leader>j <c-w>j
map <leader>k <c-w>k
map <leader>l <c-w>l

" map buffer switching

" map <F8>  : b#

" map <leader>b :b# <cr>

" I'd like to use tab to autocomplete instead of Ctrl-p

imap qq <C-p>


" some mapping for make I found on internet
map <F3> : call CompileGcc()<CR>
func! CompileGcc()
  exec "w"
    exec "!gcc % -o %<"
    endfunc

map <F4> :call CompileRunGcc()<CR>
    func! CompileRunGcc()
      exec "w"
        exec "!gcc % -o %<"
	  exec "! ./%<"
  endfunc



